[package]
edition = "2021"
name = "aoc-2021"
publish = false
version = "0.1.0"

[dependencies]
aoc-main = { version = "0.5.0", path = "../aoc-main", features = ['bench'] }
aoc-runner = "*"
aoc-runner-derive = "*"
enum-utils = "*"
itertools = "*"
lending-iterator = "0.1.6"
rayon = "*"
serde = { version = "1.0", features = ["derive"] }
serde_plain = "*"
